# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  expensestracker:
    image: expensestracker
    build:
      context: .
      dockerfile: ExpensesTracker/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5206:5206
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
